version: "3.8"

services:

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: kolleno
      POSTGRES_PASSWORD: kolleno
      POSTGRES_DB: kolleno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    restart: unless-stopped
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '.:/opt/app:z'
    depends_on:
      - db

volumes:
  postgres_data:
