# Generated by Django 5.1.5 on 2025-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("domain_name", models.CharField(max_length=255)),
                ("protocol", models.CharField(max_length=10)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("images", models.JSONField(default=list)),
                ("stylesheets_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
